[package]
name = "oxc-parser-runner"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_parser = { workspace = true }
oxc_ast = { workspace = true }
oxc_span = { workspace = true }
eframe = "0.26.0"
egui = "0.26.0"
serde_json = "1.0"
